name: GitHub ArtWork

on:
  workflow_dispatch:

jobs:
  gitart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install GitArtWork and run it
        run: |
          npx gitartwork -n khanhphan452 -t "KHANHPHAN" -f Block
